// writes the static brand-kit scenes into _studio/src (then: node _studio/render.js)
const fs = require('fs'), path = require('path'); const S = path.join(__dirname, 'src');
const mark = (w) => `<svg viewBox="0 0 40 40" style="width:${w}px"><defs><linearGradient id="lg" x1="0" x2="1"><stop offset="0" stop-color="#7df9e1"/><stop offset=".5" stop-color="#9d7bff"/><stop offset="1" stop-color="#ff7bd5"/></linearGradient><filter id="bl" x="-50%" y="-100%" width="200%" height="300%"><feGaussianBlur stdDeviation="2.4"/></filter></defs><rect x="9" y="14" width="22" height="12" fill="url(#lg)" filter="url(#bl)"/><rect x="7" y="4" width="6" height="32" rx="1" fill="#f1f0f6"/><rect x="27" y="4" width="6" height="32" rx="1" fill="#f1f0f6"/></svg>`;
const page = (body, css = '') => `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2400px;height:1350px}.pad{position:absolute;inset:110px 130px}.kick{font-family:Michroma;font-size:22px;letter-spacing:.3em;color:#64627a;text-transform:uppercase}.foot{position:absolute;left:130px;right:130px;bottom:80px;display:flex;justify-content:space-between;align-items:center;font-size:26px;letter-spacing:.18em;color:#9d9bad}.foot b{font-family:Michroma;font-weight:400;letter-spacing:.34em;color:#f1f0f6;display:flex;align-items:center;gap:22px}h1{font-family:Michroma;font-weight:400;text-transform:uppercase;line-height:1.14}.cut{clip-path:polygon(28px 0,100% 0,100% calc(100% - 28px),calc(100% - 28px) 100%,0 100%,0 28px)}${css}</style><body><div class="amb"></div><div class="scan"></div>${body}<div class="foot"><b>${mark(54)}HUSH</b><span>hushmoneyrh.xyz · @hushmoneyrh · Robinhood Chain</span></div>`;

fs.writeFileSync(path.join(S, 'hush-keyart.html'), page(`<div class="pad"><div class="kick">cloaked dollars · Robinhood Chain</div><h1 style="font-size:128px;margin-top:70px">Money that<br>doesn't <span class="iri">echo.</span></h1><p style="font-size:42px;color:#9d9bad;max-width:1250px;margin-top:60px;line-height:1.6">Mint a dollar against USDG. Cloak it. The <b style="color:#f1f0f6;font-weight:500">amount and both parties never reach the ledger.</b></p></div><div style="position:absolute;right:170px;top:560px">${mark(440)}</div>`));

const steps = [['01', 'Mint', 'Deposit USDG on Robinhood Chain. Most becomes hard collateral. The algorithmic share buys $HUSH at market and erases it.'], ['02', 'Cloak', 'Your hUSD becomes a note encrypted only to you. To everyone else the balance is unreadable.'], ['03', 'Send', 'Amount, sender and recipient stay hidden. The ledger holds one nullifier and one commitment.']];
fs.writeFileSync(path.join(S, 'hush-howitworks.html'), page(`<div class="pad"><div class="kick">how it works</div><h1 style="font-size:96px;margin-top:40px">Three moves. <span class="iri">No names.</span></h1><div class="g">${steps.map((s) => `<div class="s cut"><div class="n">${s[0]}</div><h2>${s[1]}</h2><p>${s[2]}</p></div>`).join('')}</div></div>`, `.g{display:grid;grid-template-columns:repeat(3,1fr);gap:36px;margin-top:80px}.s{background:#0e0e13dd;padding:56px 50px;height:560px;box-shadow:inset 0 0 0 1px #3a3a4a}.n{font-family:Michroma;font-size:30px;color:#7df9e1}.s h2{font-family:Michroma;font-weight:400;font-size:64px;text-transform:uppercase;margin:36px 0 30px}.s p{font-size:32px;line-height:1.6;color:#9d9bad}`));

const feats = [['Drop', 'Send cloaked dollars as a link. No address needed.'], ['Mirror', 'A read-only view key. Show one person, nobody else.'], ['Blind Desk', 'Long or short tokenized stocks. Ticker, size and P&L stay cloaked.'], ['Bonds · Cryo', '$HUSH at −20%, or lock 48h at −30% and earn 80% APY.'], ['The Window', 'Fixed-pool staking with an end date. Nothing printed.'], ['Erase', 'Every fee buys $HUSH at market and removes it from supply.'], ['Relays', 'Bring a wallet in, earn 20% of every fee it pays. Forever.'], ['Real USDG', 'Deposits verified on-chain. Withdrawals paid from a cold wallet.']];
fs.writeFileSync(path.join(S, 'hush-features.html'), page(`<div class="pad"><div class="kick">the console</div><h1 style="font-size:84px;margin-top:36px">Everything private money <span class="iri">needs.</span></h1><div class="g">${feats.map((f, i) => `<div class="f"><i>0${i + 1}</i><h2>${f[0]}</h2><p>${f[1]}</p></div>`).join('')}</div></div>`, `.g{display:grid;grid-template-columns:repeat(4,1fr);gap:0 50px;margin-top:64px}.f{border-top:1px solid #3a3a4a;padding:34px 0 46px;height:330px}.f i{font-family:Michroma;font-style:normal;font-size:20px;color:#64627a}.f h2{font-weight:500;font-size:44px;margin:16px 0 14px}.f p{font-size:27px;line-height:1.55;color:#9d9bad}`));

const rows = [['A public stablecoin transfer', '0x71c2…9e4a → 0xb03f…11d7', '$48,200.00', 0], ['A cloaked hUSD transfer', 'nullifier 9f2c…  +  commitment 4ab1…', '', 1]];
fs.writeFileSync(path.join(S, 'hush-ledger.html'), page(`<div class="pad"><div class="kick">what the ledger sees</div><h1 style="font-size:96px;margin-top:40px">Same dollar. <span class="iri">No echo.</span></h1>${rows.map((r) => `<div class="r cut"><div class="l">${r[0]}</div><div class="d"><span>${r[1]}</span><span>${r[3] ? '<em></em>' : r[2]}</span></div><div class="w">${r[3] ? 'No amount. No sender. No recipient.' : 'Everyone can read who paid whom, and how much. Forever.'}</div></div>`).join('')}</div>`, `.r{background:#0e0e13dd;box-shadow:inset 0 0 0 1px #3a3a4a;padding:46px 56px;margin-top:50px}.l{font-family:Michroma;font-size:24px;letter-spacing:.2em;text-transform:uppercase;color:#64627a}.d{display:flex;justify-content:space-between;align-items:center;font-size:56px;font-weight:400;margin:26px 0 18px}.w{font-size:32px;color:#9d9bad}em{display:block;width:420px;height:64px;background:linear-gradient(100deg,#7df9e1,#9d7bff,#ff7bd5);filter:blur(16px);border-radius:10px}`));

let r = fs.readFileSync(path.join(__dirname, 'render.js'), 'utf8');
if (!r.includes('hush-keyart')) { r = r.replace("'hush-banner': [3000, 1000],", "'hush-banner': [3000, 1000],\n  'hush-keyart': [2400, 1350],\n  'hush-howitworks': [2400, 1350],\n  'hush-features': [2400, 1350],\n  'hush-ledger': [2400, 1350],"); fs.writeFileSync(path.join(__dirname, 'render.js'), r); }
console.log('kit scenes written');
