// second wave of tweet graphics: vs ZEC/UST, Erase flywheel, Drop, Blind Desk (then: node _studio/render.js)
const fs = require('fs'), path = require('path'); const S = path.join(__dirname, 'src');
const mark = (w) => `<svg viewBox="0 0 40 40" style="width:${w}px"><defs><linearGradient id="lg" x1="0" x2="1"><stop offset="0" stop-color="#7df9e1"/><stop offset=".5" stop-color="#9d7bff"/><stop offset="1" stop-color="#ff7bd5"/></linearGradient><filter id="bl" x="-50%" y="-100%" width="200%" height="300%"><feGaussianBlur stdDeviation="2.4"/></filter></defs><rect x="9" y="14" width="22" height="12" fill="url(#lg)" filter="url(#bl)"/><rect x="7" y="4" width="6" height="32" rx="1" fill="#f1f0f6"/><rect x="27" y="4" width="6" height="32" rx="1" fill="#f1f0f6"/></svg>`;
const page = (body, css = '') => `<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="_base.css"><style>body{width:2400px;height:1350px}.pad{position:absolute;inset:100px 130px}.kick{font-family:Michroma;font-size:22px;letter-spacing:.3em;color:#64627a;text-transform:uppercase}.foot{position:absolute;left:130px;right:130px;bottom:70px;display:flex;justify-content:space-between;align-items:center;font-size:26px;letter-spacing:.18em;color:#9d9bad}.foot b{font-family:Michroma;font-weight:400;letter-spacing:.34em;color:#f1f0f6;display:flex;align-items:center;gap:22px}h1{font-family:Michroma;font-weight:400;text-transform:uppercase;line-height:1.14}.cut{clip-path:polygon(28px 0,100% 0,100% calc(100% - 28px),calc(100% - 28px) 100%,0 100%,0 28px)}.glass{display:inline-block;background:linear-gradient(100deg,#7df9e1,#9d7bff,#ff7bd5);filter:blur(14px);border-radius:10px}${css}</style><body><div class="amb"></div><div class="scan"></div>${body}<div class="foot"><b>${mark(54)}HUSH</b><span>hushmoneyrh.xyz · @hushmoneyrh · Robinhood Chain</span></div>`;

// 1 — vs ZEC and UST/LUNA
const Y = '<b class="y">YES</b>', N = '<b class="n">NO</b>';
const T = [
  ['', 'ZEC', 'UST / LUNA', 'hUSD / HUSH'],
  ['Holds $1', N + '<s>free-floating price</s>', '<b class="n">UNTIL MAY 2022</b>', Y + '<s>collateral ratio + open redemption</s>'],
  ['Private transfers', Y + '<s>shielded pool</s>', N + '<s>fully public</s>', Y + '<s>nullifier + commitment only</s>'],
  ['Hard collateral', '<b class="d">N/A</b>', '<b class="n">0%</b><s>backed by its own token</s>', '<b class="y">~90% USDG</b><s>verified on-chain</s>'],
  ['Mint prints the share token', '<b class="d">N/A</b>', '<b class="n">YES</b><s>LUNA minted on every exit</s>', '<b class="y">NEVER</b><s>mint buys $HUSH and erases it</s>'],
  ['Yield', '<b class="d">NONE</b>', '<b class="n">~20% FOREVER</b><s>subsidised, became the peg</s>', '<b class="y">FIXED POOL</b><s>hard end date</s>'],
  ['Selective disclosure', Y + '<s>viewing keys</s>', '<b class="d">N/A</b>', Y + '<s>Mirror view keys</s>'],
];
fs.writeFileSync(path.join(S, 'hush-vs.html'), page(`<div class="pad"><div class="kick">compared</div><h1 style="font-size:76px;margin-top:30px">ZEC is private. UST was a dollar.<br><span class="iri">HUSH is both.</span></h1><div class="t">${T.map((r, i) => `<div class="r${i ? '' : ' h'}">${r.map((c, j) => `<div class="c${j === 3 ? ' us' : ''}">${c}</div>`).join('')}</div>`).join('')}</div></div>`, `.t{margin-top:44px}.r{display:grid;grid-template-columns:1.15fr 1fr 1.15fr 1.25fr;border-top:1px solid #3a3a4a}.r.h{border:none}.c{padding:19px 26px;font-size:30px;font-weight:400}.r.h .c{font-family:Michroma;font-size:28px;letter-spacing:.12em;padding-bottom:22px}.c:first-child{color:#9d9bad;padding-left:0;font-size:28px;display:flex;align-items:center}.c.us{background:linear-gradient(100deg,#7df9e112,#9d7bff1c,#ff7bd514)}.r.h .c.us{background:linear-gradient(100deg,#7df9e1,#9d7bff,#ff7bd5);color:#0a0a10}b{font-weight:600;display:block;letter-spacing:.06em}b.y{color:#7df9e1}b.n{color:#ff6b81}b.d{color:#64627a}s{text-decoration:none;display:block;font-size:22px;color:#9d9bad;font-weight:300;margin-top:2px}`));

// 2 — Erase flywheel
const F = [['You use hUSD', 'cloak · send · uncloak · redeem'], ['Fees collect in USDG', '30 bps · 50 bps on redeem'], ['Protocol buys $HUSH', 'at market, every cycle'], ['$HUSH is erased', 'public receipt, permanent']];
fs.writeFileSync(path.join(S, 'hush-erase.html'), page(`<div class="pad"><div class="kick">erase · buyback</div><h1 style="font-size:92px;margin-top:36px">Every fee buys $HUSH<br><span class="iri">and deletes it.</span></h1><div class="g">${F.map((f, i) => `<div class="s cut"><i>0${i + 1}</i><h2>${f[0]}</h2><p>${f[1]}</p></div>${i < 3 ? '<div class="ar">→</div>' : ''}`).join('')}</div><p class="w">Plus: the algorithmic slice of <b>every mint</b> also buys $HUSH and erases it. Nothing is ever printed to pay for it.<br>More private dollars moving means less $HUSH existing.</p></div>`, `.g{display:grid;grid-template-columns:1fr 70px 1fr 70px 1fr 70px 1fr;align-items:center;margin-top:70px}.s{background:#0e0e13dd;box-shadow:inset 0 0 0 1px #3a3a4a;padding:40px 36px;height:330px}.s i{font-family:Michroma;font-style:normal;font-size:24px;color:#7df9e1}.s h2{font-weight:500;font-size:42px;line-height:1.2;margin:26px 0 16px}.s p{font-size:26px;color:#9d9bad}.ar{text-align:center;font-size:54px;color:#9d7bff}.g .s:last-child{background:linear-gradient(100deg,#7df9e11c,#9d7bff26,#ff7bd51c)}.w{font-size:34px;line-height:1.6;color:#9d9bad;margin-top:60px;max-width:1900px}.w b{color:#f1f0f6;font-weight:500}`));

// 3 — Drop
fs.writeFileSync(path.join(S, 'hush-drop.html'), page(`<div class="pad"><div class="kick">drop · pay link</div><h1 style="font-size:100px;margin-top:36px">Send private dollars<br><span class="iri">as a link.</span></h1><div class="lk cut"><span>hushmoneyrh.xyz/#claim=</span><em class="glass"></em></div><div class="g"><div><i>01</i><h2>Lock</h2><p>Put cloaked hUSD behind a random secret. No recipient address needed.</p></div><div><i>02</i><h2>Share</h2><p>Text it. DM it. Print it as a QR. The secret lives only in the link.</p></div><div><i>03</i><h2>Claim</h2><p>Whoever opens it receives the hUSD straight into their own cloaked balance.</p></div></div><p class="w">On the ledger: one nullifier, one commitment. Identical to any cloaked send. One claim per Drop.</p></div>`, `.lk{margin-top:54px;background:#0e0e13dd;box-shadow:inset 0 0 0 1px #3a3a4a;padding:40px 50px;font-size:54px;font-weight:400;display:flex;align-items:center;gap:20px;color:#7df9e1}.lk em{width:760px;height:60px}.g{display:grid;grid-template-columns:repeat(3,1fr);gap:60px;margin-top:56px}.g>div{border-top:1px solid #3a3a4a;padding-top:28px}.g i{font-family:Michroma;font-style:normal;font-size:22px;color:#64627a}.g h2{font-weight:500;font-size:46px;margin:12px 0 12px}.g p{font-size:29px;line-height:1.55;color:#9d9bad}.w{font-size:30px;color:#9d9bad;margin-top:44px}`));

// 4 — Blind Desk
const M = ['HOOD', 'TSLA', 'NVDA', 'AAPL', 'SPY', 'COIN', 'MSTR', 'GLD', 'BTC', 'ETH'];
fs.writeFileSync(path.join(S, 'hush-blinddesk.html'), page(`<div class="pad"><div class="kick">blind desk</div><h1 style="font-size:100px;margin-top:36px">Trade stocks.<br><span class="iri">Show nobody.</span></h1><div class="tp">${M.map((m) => `<div>${m}</div>`).join('')}</div><div class="g"><div class="cut"><div class="l">what you see</div><div class="p"><span>LONG NVDA · 1x</span><b style="color:#7df9e1">+ 42.18 hUSD</b></div><div class="p"><span>SHORT TSLA · 1x</span><b style="color:#ff6b81">− 9.60 hUSD</b></div></div><div class="cut"><div class="l">what everyone else sees</div><div class="p"><em class="glass" style="width:420px;height:44px"></em><em class="glass" style="width:230px;height:44px"></em></div><div class="p"><em class="glass" style="width:380px;height:44px"></em><em class="glass" style="width:200px;height:44px"></em></div></div></div><p class="w">Long or short at 1x, priced off the live exchange tape, settled in cloaked hUSD. Ticker, size, side and P&amp;L never reach the ledger. 30 bps each way goes to Erase.</p></div>`, `.tp{display:grid;grid-template-columns:repeat(10,1fr);gap:2px;margin-top:50px}.tp div{background:#0e0e13dd;box-shadow:inset 0 0 0 1px #3a3a4a;text-align:center;padding:22px 0;font-family:Michroma;font-size:26px;letter-spacing:.08em}.g{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:40px}.g>div{background:#0e0e13dd;box-shadow:inset 0 0 0 1px #3a3a4a;padding:36px 44px}.l{font-family:Michroma;font-size:20px;letter-spacing:.22em;text-transform:uppercase;color:#64627a;margin-bottom:10px}.p{display:flex;justify-content:space-between;align-items:center;font-size:40px;font-weight:400;padding:18px 0;border-top:1px solid #ffffff12}.p b{font-weight:500}.w{font-size:30px;line-height:1.6;color:#9d9bad;margin-top:40px;max-width:2000px}`));

let r = fs.readFileSync(path.join(__dirname, 'render.js'), 'utf8');
if (!r.includes('hush-vs')) { r = r.replace("'hush-ledger': [2400, 1350],", "'hush-ledger': [2400, 1350],\n  'hush-vs': [2400, 1350],\n  'hush-erase': [2400, 1350],\n  'hush-drop': [2400, 1350],\n  'hush-blinddesk': [2400, 1350],"); fs.writeFileSync(path.join(__dirname, 'render.js'), r); }
console.log('kit2 scenes written');
